version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/python
      
jobs:
  build-my-project:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

workflows:
  my-custom-workflow:
    jobs:
      - build-my-project